.TH "Node" 3 "Sun Mar 5 2017" "Version 0.001" "Data Structures - LinkedList - DocTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Node\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.ti -1c
.RI "\fBNode\fP (int)"
.br
.ti -1c
.RI "\fBNode\fP (int, \fBNode\fP *)"
.br
.ti -1c
.RI "\fBNode\fP (const \fBNode\fP &)"
.br
.ti -1c
.RI "\fB~Node\fP ()"
.br
.ti -1c
.RI "void \fBsetData\fP (int)"
.br
.ti -1c
.RI "void \fBsetNext\fP (\fBNode\fP *)"
.br
.ti -1c
.RI "int \fBgetData\fP ()"
.br
.ti -1c
.RI "\fBNode\fP * \fBgetNext\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Node::Node ()"

.SS "Node::Node (int data)"

.SS "Node::Node (int data, \fBNode\fP * next)"

.SS "Node::Node (const \fBNode\fP & node)"

.SS "Node::~Node ()"

.SH "Member Function Documentation"
.PP 
.SS "int Node::getData ()"

.SS "\fBNode\fP * Node::getNext ()"

.SS "void Node::setData (int data)"

.SS "void Node::setNext (\fBNode\fP * next)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Data Structures - LinkedList - DocTest from the source code\&.
