.TH "D:/Git/DataStructures/LinkedList/main.cpp" 3 "Sun Mar 5 2017" "Version 0.001" "Data Structures - LinkedList - DocTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Git/DataStructures/LinkedList/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'List\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Data Structures - LinkedList - DocTest from the source code\&.
